name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Hola Jefa'
        run: echo "mi primera automatizacion jefa"
      - name: Dime que fecha es
        run: Date
      - name: Muestrame el directorio de contendio
        run: ls -la